### ISSUE TITLE
Invalid context throws into Run

### ISSUE THREAD

**Issue by icron** [andrskom/gomultitask#4]
I think, here https://github.com/andrskom/gomultitask/blob/master/operator.go#L80
must be `internalCtx` instead just `ctx`.

That is why the code not working:

```go
func (t *TaskLoader) Run(c context.Context) error {
	for {
		select {
		case <-time.After(10 * time.Second):
			err := t.worker()
			if err != nil {
				t.log.Error("Error happened", zap.Error(err))
			}
		case <-c.Done(): // 
			fmt.Println("THE CODE NEVER HAPPENED AFTER SHUTDOWN SCRIPT!!!")
			return nil
		}
	}
}
```

**Comment by andrskom** [comment]
There is context of your run, for example. You want to run something with timeout 10 seconds. Internal is ctx for system routines.

**Comment by icron** [comment]
Ok. thanks
